---
downloads: ~/.ansible-downloads/

configure_dotfiles: no
configure_sudoers: no
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - autoconf
  - awscli
  - bash-completion
  - cowsay
  - docker-machine-parallels
  - doxygen
  - ec2-api-tools
  - gettext
  - gifsicle
  - git
  - git-flow
  - git-lfs
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - lua
  - mcrypt
  - nmap
  - node
  - nvm
  - osxutils
  - php
  - pkg-config
  - saml2aws
  - ssh-copy-id
  - sqlite
  - readline
  - rmtrash
  - openssl
  - pv
  - tmux
  - unrar
  - wget
  - wrk

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - versent/homebrew-taps

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - AdoptOpenJDK
  - alfred
  - bartender
  - bbedit
  - devonthink
  - docker
  - dropzone
  - geekbench
  - geektool
  - iterm2
  - licecap
  - macvim
  - omnifocus
  - omnigraffle
  - omnioutliner
  - omniplan
  - omnipresence
  - pacifist
  - packages
  - parallels
  - parallels-toolbox
  - parallels-virtualization-sdk
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlprettypatch
  - qlstephen
  - quicklook-csv
  - quicklook-json
  - sequel-pro
  - spideroakone
  - skitch
  - suspicious-package
  - vagrant
  - wineskin-winery
  - xquartz

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
